### ISSUE TITLE
RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible

### ISSUE THREAD

**Issue by farazBhatti** [onnx/tutorials#137]
I am following [this](https://github.com/onnx/tutorials/blob/master/examples/CoreML/ONNXLive/README.md#download-or-train-pytorch-style-transfer-models) tutorial , but when i run the following commands
 
`python ./neural_style/neural_style.py eval --content-image dummy.jpg --output-image dummy-out.jpg --model ./saved_models/candy.pth --cuda 0 --export_onnx ./saved_models/candy.onnx
python ./neural_style/neural_style.py eval --content-image dummy.jpg --output-image dummy-out.jpg --model ./saved_models/udnie.pth --cuda 0 --export_onnx ./saved_models/udnie.onnx
python ./neural_style/neural_style.py eval --content-image dummy.jpg --output-image dummy-out.jpg --model ./saved_models/rain_princess.pth --cuda 0 --export_onnx ./saved_models/rain_princess.onnx
python ./neural_style/neural_style.py eval --content-image dummy.jpg --output-image dummy-out.jpg --model ./saved_models/mosaic.pth --cuda 0 --export_onnx ./saved_models/mosaic.onnx`

i get the above mentioned error in the title. Any suggestions?

python - 3..6.8
ubuntu - 18
torch 1.1.0

**Comment by Ramanpreet6262** [comment]
@farazBhatti Please refer to this commit https://github.com/pytorch/pytorch/pull/20116/commits/11845cf2440c1abb0cb117bcee9532b26573e9c9

Go to file symbolic.py in onnx directory (for its path see error on your terminal like in my case it was - /home/adam/anaconda3/lib/python3.6/site-packages/torch/onnx/symbolic.py).
Head to this file and make required changes and it will work.

**Comment by farazBhatti** [comment]
@Ramanpreet6262 , i ve applied your suggestion and it worked out just fine. thank you very much....

**Comment by lfpan** [comment]
Can you elaborate on how you changed it? I also encountered the same problem, but I don't know how to modify the symbolic.py file. @farazBhatti

**Comment by farazBhatti** [comment]
Hi @lfpan , which version of torch are you using? i couldnt replicate above problem when using the latest commit. kindly uninstall old version and install new one. it should work fine.

**Comment by lfpan** [comment]
I tried pytorch1.1.0 and pytorch1.2.0, both of which will have the above problem. @farazBhatti

**Comment by farazBhatti** [comment]
use virtual environment if not already using. simply go to folder containing the file and replace line colored in red with green ones(as showen here: pytorch/pytorch@11845cf ).my file was in path
/home/faraz/anaconda3/lib/python3.6/site-packages/torch/onnx/symbolic.py.
go to your home folder and simply follow the address/path keep opening folder given in your path(see error for your path). are you having problem of opening file or is it something else?

**Comment by mengban** [comment]
> use virtual environment if not already using. simply go to folder containing the file and replace line colored in red with green ones(as showen here: [pytorch/pytorch@11845cf](https://github.com/pytorch/pytorch/commit/11845cf) ).my file was in path
> /home/faraz/anaconda3/lib/python3.6/site-packages/torch/onnx/symbolic.py.
> go to your home folder and simply follow the address/path keep opening folder given in your path(see error for your path). are you having problem of opening file or is it something else?
I use pytorch1.1.0.
I followed what u said, but it didn't work. I logged in the server and make sure that the  symbolic.py has changed. what should i do next?

**Comment by farazBhatti** [comment]
uninstall torch, download pytorch repo from github,do the required changes and import modified(in which you have applied changes) directly from your code ,instead of importing installed pytorch. make sure to uninstall it completely and put pytorch (downloded for github) in the same folder in which you have your code for tutorial.this way code will import that pytorch which has been modified by you rather importing that which is already installed(make sure to uninstall it completely)

**Comment by mengban** [comment]
🇶🇦 

> uninstall torch, download pytorch repo from github,do the required changes and import modified(in which you have applied changes) directly from your code ,instead of importing installed pytorch. make sure to uninstall it completely and put pytorch (downloded for github) in the same folder in which you have your code for tutorial.this way code will import that pytorch which has been modified by you rather importing that which is already installed(make sure to uninstall it completely). Maybe this could help..

Thanks for your reply. But when I read the issue carefully, I found that I didn't use the the **Upsample** in my model. So I think maybe it's my model appears sth wrong. I use [The model i used here:mobilenet v3](https://github.com/shaoshengsong/MobileNetV3-SSD/blob/master/vision/ssd/mobilenet_v3_ssd_lite.py).

**Comment by saulzar** [comment]
I have the same issue - same error and no use of Upsample at all

**Comment by anuar12** [comment]
I think it's a general problem when the input to the functional layer is dynamic. 
I had a situation where functional avg_pool3d that depended on the shape of the previous layer's outputs. One has to either make the kernel constant or switch to non-functional pytorch's api.

**Comment by liuhe2017** [comment]
> @farazBhatti Please refer to this commit [pytorch/pytorch@11845cf](https://github.com/pytorch/pytorch/commit/11845cf2440c1abb0cb117bcee9532b26573e9c9)
> 
> Go to file symbolic.py in onnx directory (for its path see error on your terminal like in my case it was - /home/adam/anaconda3/lib/python3.6/site-packages/torch/onnx/symbolic.py).
> Head to this file and make required changes and it will work.

Excuse me, I have modified symbolic.py but still got the same error. 
python - 3.6.9
ubuntu - 16.04
torch 1.1.0
Could u help me to solve this problem?

**Comment by liuhe2017** [comment]
I have modified symbolic.py but still got the same error.
python - 3.6.9
ubuntu - 16.04
torch 1.1.0

**Comment by farazBhatti** [comment]
@liuhe2017  make sure that you are importing torch which has modified symbolic.py

**Comment by liuhe2017** [comment]
> @liuhe2017 make sure that you are importing torch which has modified symbolic.py

Yeah, I try to put some unreadable code in symbolic.py to make sure modified symbolic.py

**Comment by liuhe2017** [comment]
> @liuhe2017 make sure that you are importing torch which has modified symbolic.py
My partial code is:
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter('runs/original-vehicle-pose-estimation')
# write to tensorboard
writer.add_image('four_fashion_mnist_images', img_grid)
model = MyUNet(8).to(device)
optimizer = optim.Adam(model.parameters(), lr=0.001)
exp_lr_scheduler = lr_scheduler.StepLR(optimizer, step_size=max(n_epochs, 10) * len(train_loader) // 3, gamma=0.1)
img_batch = img_batch.to(device)
optimizer.zero_grad()
torch.cuda.empty_cache()
with writer:
    writer.add_graph(model, (img_batch,))
writer.close()
The environment is:
python 3.6.9
pytorch 1.1
The error is:
/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/numpy/core/function_base.py:22: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  i = operator.index(i)
/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/numpy/lib/shape_base.py:1227: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if all(x == 1 for x in tup) and isinstance(A, _nx.ndarray):
/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/numpy/lib/shape_base.py:1241: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if nrep != 1:
/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/numpy/lib/shape_base.py:1244: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return c.reshape(shape_out)
/home/lhcoder/PycharmProjects/pose-estimation/model.py:302: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  mesh = torch.cat([torch.tensor(mg_x).to(device), torch.tensor(mg_y).to(device)], 1)
Traceback (most recent call last):
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 298, in graph
    _optimize_trace(trace, operator_export_type)
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 231, in _optimize_trace
    trace.set_graph(_optimize_graph(trace.graph(), operator_export_type))
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 262, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/onnx/__init__.py", line 50, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/onnx/utils.py", line 589, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 130, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 130, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 90, in _parse_arg
    raise RuntimeError("Failed to export an ONNX attribute, "
RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lhcoder/PycharmProjects/pose-estimation/model.py", line 405, in <module>
    writer.add_graph(model, (img_batch,))
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 534, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 303, in graph
    logging.warn(ImportError(e))
NameError: name 'logging' is not defined

**Comment by liuhe2017** [comment]
Yeah, I try to put some unreadable code in symbolic.py to make sure modified symbolic.py
My partial code is:
from torch.utils.tensorboard import SummaryWriter
writer = SummaryWriter('runs/original-vehicle-pose-estimation')
# write to tensorboard
writer.add_image('four_fashion_mnist_images', img_grid)
model = MyUNet(8).to(device)
optimizer = optim.Adam(model.parameters(), lr=0.001)
exp_lr_scheduler = lr_scheduler.StepLR(optimizer, step_size=max(n_epochs, 10) * len(train_loader) // 3, gamma=0.1)
img_batch = img_batch.to(device)
optimizer.zero_grad()
torch.cuda.empty_cache()
with writer:
    writer.add_graph(model, (img_batch,))
writer.close()
The environment is:
python 3.6.9
pytorch 1.1
The error is:
/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/numpy/core/function_base.py:22: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  i = operator.index(i)
/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/numpy/lib/shape_base.py:1227: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if all(x == 1 for x in tup) and isinstance(A, _nx.ndarray):
/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/numpy/lib/shape_base.py:1241: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if nrep != 1:
/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/numpy/lib/shape_base.py:1244: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return c.reshape(shape_out)
/home/lhcoder/PycharmProjects/pose-estimation/model.py:302: TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  mesh = torch.cat([torch.tensor(mg_x).to(device), torch.tensor(mg_y).to(device)], 1)
Traceback (most recent call last):
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 298, in graph
    _optimize_trace(trace, operator_export_type)
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 231, in _optimize_trace
    trace.set_graph(_optimize_graph(trace.graph(), operator_export_type))
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 262, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/onnx/__init__.py", line 50, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/onnx/utils.py", line 589, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 130, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 130, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 90, in _parse_arg
    raise RuntimeError("Failed to export an ONNX attribute, "
RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lhcoder/PycharmProjects/pose-estimation/model.py", line 405, in <module>
    writer.add_graph(model, (img_batch,))
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 534, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose, **kwargs))
  File "/home/lhcoder/anaconda2/envs/py36_torch1/lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 303, in graph
    logging.warn(ImportError(e))
NameError: name 'logging' is not defined

**Comment by DuckJ** [comment]
> 🇶🇦
> 
> > uninstall torch, download pytorch repo from github,do the required changes and import modified(in which you have applied changes) directly from your code ,instead of importing installed pytorch. make sure to uninstall it completely and put pytorch (downloded for github) in the same folder in which you have your code for tutorial.this way code will import that pytorch which has been modified by you rather importing that which is already installed(make sure to uninstall it completely). Maybe this could help..
> 
> Thanks for your reply. But when I read the issue carefully, I found that I didn't use the the **Upsample** in my model. So I think maybe it's my model appears sth wrong. I use [The model i used here:mobilenet v3](https://github.com/shaoshengsong/MobileNetV3-SSD/blob/master/vision/ssd/mobilenet_v3_ssd_lite.py).

have you sloved this problem? I also meet this question when convert the mobv3 to onnx

**Comment by malemo** [comment]
I still have this problem. Please [see](https://github.com/pytorch/pytorch/issues/34743)

**Comment by Akshaysharma29** [comment]
Hi all, Have anyone of you have figured out this issue? I have also updated the symbolic_opset9.py 
Using Pytorch:1.2
Thanks.

**Comment by padmasreenagarajan** [comment]
hi... even i faced the same error when importing mobilenetv3 to onnx..

**Failed to export an ONNX attribute 'onnx::Gather', since it's not constant, please try to make things (e.g., kernel size) static if possible**
could u suggest some solution pls?
@DuckJ @malemo @Akshaysharma29

**Comment by CeyangGeng** [comment]
> I think it's a general problem when the input to the functional layer is dynamic.
> I had a situation where functional avg_pool3d that depended on the shape of the previous layer's outputs. One has to either make the kernel constant or switch to non-functional pytorch's api.

I meet the problem caused by non-constant kernal. Could you tell me how to switch to non-functional api? Thanks for your time~

**Comment by AhmadBaracat** [comment]
I used to have the same error when exporting using `torch.onnx.export(model, x, ONNX_FILE_PATH` and I fixed it by specifying the `opset_version` like so: `torch.onnx.export(model, x, ONNX_FILE_PATH, opset_version = 11)`

**Comment by 91dana** [comment]
> I used to have the same error when exporting using `torch.onnx.export(model, x, ONNX_FILE_PATH)` and I fixed it by specifying the `opset_version` like so: `torch.onnx.export(model, x, ONNX_FILE_PATH, opset_version = 11)`

This worked for me! Thanks a lot!!!

**Comment by nakairika** [comment]
I changed ```opset_version ==11``` and it's not working, so I fixed it by adding the codes following:
```python
# before
def forward(self, x):
    height, width = x.size()[2:]
    out = F.avg_pool2d(x, [height, width])
    return out 
```
```python
# after
def forward(self, x):
    height, width = x.size()[2:]
    if torch.is_tensor(height):
       height = height.item()
        width = width.item() 
    out = F.avg_pool2d(x, [height, width])
    return out 
```

**Comment by AloneGu** [comment]
try

```
# after
def forward(self, x):
    out = F.adaptive_avg_pool2d(x, 1)
    return out 
```

> I changed `opset_version ==11~14` and it's not working, so I fixed it by adding the codes following:
> 
> ```python
> # before
> def forward(self, x):
>     height, width = x.size()[2:]
>     out = F.avg_pool2d(x, [height, width])
>     return out 
> ```
> 
> ```python
> # after
> def forward(self, x):
>     height, width = x.size()[2:]
>     if torch.is_tensor(height):
>        height = height.item()
>         width = width.item() 
>     out = F.avg_pool2d(x, [height, width])
>     return out 
> ```

```
# before
def forward(self, x):
    height, width = x.size()[2:]
    out = F.avg_pool2d(x, [height, width])
    return out 
```
